# Generated by Django 4.2.3 on 2023-08-04 12:00

from django.db import migrations, models
import server.models
import server.validator


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0003_category_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="banner",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=server.models.server_banner_upload_path,
                validators=[server.validator.validate_image_file_extension],
            ),
        ),
        migrations.AddField(
            model_name="channel",
            name="icons",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=server.models.server_icon_upload_path,
                validators=[
                    server.validator.validate_image_file_extension,
                    server.validator.validate_icon_image_size,
                ],
            ),
        ),
    ]
